### ISSUE TITLE
Unable to compile sketch

### ISSUE THREAD

**Issue by t3ch9** [Jayby18/CCS811-HDC1080#1] opened 2020-10-16 22:59 UTC
Hello, getting the following error when I try to compile the sketch:

Arduino: 1.8.12 (Windows 7), Board: "Arduino Uno"

C:\Users\admin\Documents\Arduino\CCS811-HDC1080\CCS811-HDC1080.ino: In function 'void loop()':

CCS811-HDC1080:113:5: error: expected primary-expression before '}' token

     }

     ^

exit status 1
expected primary-expression before '}' token

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by jadenaccord** [comment] 2020-10-17 19:26
I was unable to reproduce this error. When I tried to compile this (on both my Windows and Linux machine), the code compiles with no errors.

Would you mind pasting the entire loop function from your local file, so I can check that your syntax is not slightly different than mine? The error suggests that there might be a '}' too little or too many.

**Comment by t3ch9** [comment] 2020-10-17 19:30
Its the same exact code copy/paste from your ino file.

One thing that I noticed is that on line 106 is missing a closing parenthesis. 

If possible, please upload the ino file that you are using on your local machine.

**Comment by jadenaccord** [comment] 2020-10-17 19:45
You're completely right. I didn't notice that I fixed that missing closing parenthesis on line 106, but didn't commit it.
There's also a missing semicolon on line 112.

I fixed those and making a pull request now.

**Comment by t3ch9** [comment] 2020-10-17 20:31
I updated my sketch based on the corrections in your previous comment.  Now I am able to compile the sketch, however in serial console I get:   Failed to start sensor! Please check your wiring.

Are you using the same exact wiring on your Arduino as the Wemos D1 / ESP32 wiring on CJMCU-8118_InfluxDB ?

If not, which wiring are you using on your Arduino?

**Comment by jadenaccord** [comment] 2020-10-17 20:39
I wired it like so:

- VCC - 3.3V
- GND - G
- SCL - A5
- SDA - A4
- WAK - G

This is because the I2C protocol only works on analog pinouts 4 and 5 on the Arduino Uno, not the digital pinouts 1 and 2 like on the Wemos D1.

**Comment by t3ch9** [comment] 2020-10-17 20:52
Your wiring works on my Arduino...now getting the sensor readings on my serial monitor. Thank you. 

Did you have to calibrate or do anything special to this sensor?

**Comment by jadenaccord** [comment] 2020-10-17 21:16
There is no calibration required, but I have found the measurements to become more stable after waiting maybe 20 minutes.

According to [this thread about reliability](https://github.com/maarten-pennings/CCS811/issues/8#issuecomment-447673043) between [bfaliszek](https://github.com/bfaliszek) (whose code I based this on) and [maarten-pennings](https://github.com/maarten-pennings) (who also wrote a library for the CCS811), giving the sensor about a week will make it more stable. I haven't had it running for that long without interruption, so I can't personally attest to that.

That same thread also has some mentions of firmware updates. I personally have not tried that yet either, but it might be worth it if you want better measurements.

I hope this helps. And if you don't mind me asking, how did you find this repository? Via Google, GitHub search, or something else?

**Comment by t3ch9** [comment] 2020-10-17 21:32
I found this repo via GitHub search.  Thank you for all your feedback.

**Closed as completed** 2020-10-17 21:34 UTC
